spring:
  datasource:
    url: jdbc:mysql://47.95.145.177:3306/godspen_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 达梦数据库
    # url: jdbc:dm://192.168.90.125:5236/regdb
    # username: regdb
    # password: hongyi2020
    # driver-class-name: dm.jdbc.driver.DmDriver
mybatis:
  configuration:
    map-underscore-to-camel-case: true