spring:
  datasource:
    url: jdbc:mysql://47.95.145.177:3306/godspen_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true